services:
  my_zookeeper:
    image: zookeeper:latest
    container_name: my_zookeeper
    restart: always
    ports:
      - "2181:2181"

  my_kafka:
    image: confluentinc/cp-kafka:latest
    container_name: my_kafka
    restart: always
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: 192.168.29.98:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.29.98:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  restaurant_service_db:
    image: postgres
    container_name: my_restaurant_postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: nest123
      POSTGRES_DB: restaurant_service_db
    volumes:
      - postgres-data:/var/lib/postgresql/data

  order_service_db:
    image: postgres
    container_name: my_order_postgres
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: nest123
      POSTGRES_DB: order_service_db
    volumes:
      - postgres-data:/var/lib/postgresql/data

  user_service_db:
    image: postgres
    container_name: my_user_postgres
    restart: always
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: nest123
      POSTGRES_DB: user_service_db
    volumes:
      - postgres-data:/var/lib/postgresql/data

  delivery_service_db:
    image: postgres
    container_name: my_delivery_postgres
    restart: always
    ports:
      - "5436:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: nest123
      POSTGRES_DB: delivery_service_db
    volumes:
      - postgres-data:/var/lib/postgresql/data

  payment_service_db:
    image: postgres
    container_name: my_payment_postgres
    restart: always
    ports:
      - "5437:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: nest123
      POSTGRES_DB: payment_service_db
    volumes:
      - postgres-data:/var/lib/postgresql/data

  notification_service_db:
    image: postgres
    container_name: my_notification_postgres
    restart: always
    ports:
      - "5438:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: nest123
      POSTGRES_DB: notification_service_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
  redis:
    image: redis
    restart: always
    container_name: my_redis
    ports:
      - "6379:6379"

volumes:
  postgres-data:


