services:
  my_zookeeper:
    image: zookeeper:latest
    container_name: my_zookeeper
    restart: always
    ports:
      - "2181:2181"

  my_kafka:
    image: confluentinc/cp-kafka:latest
    container_name: my_kafka
    restart: always
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: 192.168.29.98:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.29.98:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  logging_service_db:
    image: postgres
    container_name: my_logging_postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: nest123
      POSTGRES_DB: logging_service_db
    volumes:
      - postgres-data:/var/lib/postgresql/data

  ridder_service_db:
    image: postgres
    container_name: my_ridder_postgres
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: nest123
      POSTGRES_DB: ridder_service_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
  redis:
    image: redis
    restart: always
    container_name: my_redis
    ports:
      - "6379:6379"

volumes:
  postgres-data:


